"""pagos repartidos entre varios documentos

Revision ID: 060bd9f486a9
Revises: cc2648d23443
Create Date: 2026-09-26 18:25:10.326194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.tipos


# revision identifiers, used by Alembic.
revision: str = '060bd9f486a9'
down_revision: Union[str, Sequence[str], None] = 'cc2648d23443'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pagos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('cobro', 'pago', name='tipomovimiento', native_enum=False, length=20), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('proveedor_id', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('monto', app.tipos.DecimalFijo(), nullable=False),
    sa.Column('metodo', sa.Enum('efectivo', 'transferencia', 'cheque', 'tarjeta', 'otro', name='metodopago', native_enum=False, length=20), nullable=False),
    sa.Column('referencia', sa.String(length=80), nullable=True),
    sa.Column('notas', sa.String(length=300), nullable=True),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("(tipo = 'cobro' AND cliente_id IS NOT NULL AND proveedor_id IS NULL) OR (tipo = 'pago' AND proveedor_id IS NOT NULL AND cliente_id IS NULL)", name=op.f('ck_pagos_contraparte_segun_tipo')),
    sa.CheckConstraint('monto > 0', name=op.f('ck_pagos_monto_positivo')),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], name=op.f('fk_pagos_cliente_id_clientes')),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], name=op.f('fk_pagos_proveedor_id_proveedores')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pagos'))
    )
    with op.batch_alter_table('pagos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pagos_cliente_id'), ['cliente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pagos_fecha'), ['fecha'], unique=False)
        batch_op.create_index(batch_op.f('ix_pagos_proveedor_id'), ['proveedor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pagos_tipo'), ['tipo'], unique=False)

    op.create_table('aplicaciones_pago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pago_id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=True),
    sa.Column('orden_id', sa.Integer(), nullable=True),
    sa.Column('monto', app.tipos.DecimalFijo(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('(pedido_id IS NOT NULL AND orden_id IS NULL) OR (pedido_id IS NULL AND orden_id IS NOT NULL)', name=op.f('ck_aplicaciones_pago_un_solo_documento')),
    sa.CheckConstraint('monto > 0', name=op.f('ck_aplicaciones_pago_monto_positivo')),
    sa.ForeignKeyConstraint(['orden_id'], ['ordenes_compra.id'], name=op.f('fk_aplicaciones_pago_orden_id_ordenes_compra')),
    sa.ForeignKeyConstraint(['pago_id'], ['pagos.id'], name=op.f('fk_aplicaciones_pago_pago_id_pagos')),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos_cliente.id'], name=op.f('fk_aplicaciones_pago_pedido_id_pedidos_cliente')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_aplicaciones_pago')),
    sa.UniqueConstraint('pago_id', 'orden_id', name=op.f('uq_aplicaciones_pago_pago_id')),
    sa.UniqueConstraint('pago_id', 'pedido_id', name=op.f('uq_aplicaciones_pago_pago_id'))
    )
    with op.batch_alter_table('aplicaciones_pago', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_aplicaciones_pago_orden_id'), ['orden_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_aplicaciones_pago_pago_id'), ['pago_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_aplicaciones_pago_pedido_id'), ['pedido_id'], unique=False)

    with op.batch_alter_table('cobros_cliente', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cobros_cliente_fecha'))
        batch_op.drop_index(batch_op.f('ix_cobros_cliente_pedido_id'))

    op.drop_table('cobros_cliente')
    with op.batch_alter_table('pagos_proveedor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pagos_proveedor_fecha'))
        batch_op.drop_index(batch_op.f('ix_pagos_proveedor_orden_id'))

    op.drop_table('pagos_proveedor')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pagos_proveedor',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('orden_id', sa.INTEGER(), nullable=False),
    sa.Column('fecha', sa.DATE(), nullable=False),
    sa.Column('monto', sa.BIGINT(), nullable=False),
    sa.Column('metodo', sa.VARCHAR(length=20), nullable=False),
    sa.Column('referencia', sa.VARCHAR(length=80), nullable=True),
    sa.Column('notas', sa.VARCHAR(length=300), nullable=True),
    sa.Column('creado_en', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actualizado_en', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('monto > 0', name=op.f('ck_pagos_proveedor_monto_positivo')),
    sa.ForeignKeyConstraint(['orden_id'], ['ordenes_compra.id'], name=op.f('fk_pagos_proveedor_orden_id_ordenes_compra')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pagos_proveedor'))
    )
    with op.batch_alter_table('pagos_proveedor', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pagos_proveedor_orden_id'), ['orden_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pagos_proveedor_fecha'), ['fecha'], unique=False)

    op.create_table('cobros_cliente',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('pedido_id', sa.INTEGER(), nullable=False),
    sa.Column('fecha', sa.DATE(), nullable=False),
    sa.Column('monto', sa.BIGINT(), nullable=False),
    sa.Column('metodo', sa.VARCHAR(length=20), nullable=False),
    sa.Column('referencia', sa.VARCHAR(length=80), nullable=True),
    sa.Column('notas', sa.VARCHAR(length=300), nullable=True),
    sa.Column('creado_en', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actualizado_en', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('monto > 0', name=op.f('ck_cobros_cliente_monto_positivo')),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos_cliente.id'], name=op.f('fk_cobros_cliente_pedido_id_pedidos_cliente')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cobros_cliente'))
    )
    with op.batch_alter_table('cobros_cliente', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cobros_cliente_pedido_id'), ['pedido_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cobros_cliente_fecha'), ['fecha'], unique=False)

    with op.batch_alter_table('aplicaciones_pago', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_aplicaciones_pago_pedido_id'))
        batch_op.drop_index(batch_op.f('ix_aplicaciones_pago_pago_id'))
        batch_op.drop_index(batch_op.f('ix_aplicaciones_pago_orden_id'))

    op.drop_table('aplicaciones_pago')
    with op.batch_alter_table('pagos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pagos_tipo'))
        batch_op.drop_index(batch_op.f('ix_pagos_proveedor_id'))
        batch_op.drop_index(batch_op.f('ix_pagos_fecha'))
        batch_op.drop_index(batch_op.f('ix_pagos_cliente_id'))

    op.drop_table('pagos')
    # ### end Alembic commands ###
