"""gastos de operacion

Revision ID: 288af92b4c5d
Revises: 060bd9f486a9
Create Date: 2026-09-26 19:09:52.591302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.tipos


# revision identifiers, used by Alembic.
revision: str = '288af92b4c5d'
down_revision: Union[str, Sequence[str], None] = '060bd9f486a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gastos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('categoria', sa.String(length=40), nullable=False),
    sa.Column('concepto', sa.String(length=200), nullable=False),
    sa.Column('monto', app.tipos.DecimalFijo(), nullable=False),
    sa.Column('metodo', sa.Enum('efectivo', 'transferencia', 'cheque', 'tarjeta', 'otro', name='metodopago', native_enum=False, length=20), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=True),
    sa.Column('referencia', sa.String(length=80), nullable=True),
    sa.Column('notas', sa.String(length=300), nullable=True),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('monto > 0', name=op.f('ck_gastos_monto_positivo')),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], name=op.f('fk_gastos_proveedor_id_proveedores')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gastos'))
    )
    with op.batch_alter_table('gastos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gastos_categoria'), ['categoria'], unique=False)
        batch_op.create_index(batch_op.f('ix_gastos_fecha'), ['fecha'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gastos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gastos_fecha'))
        batch_op.drop_index(batch_op.f('ix_gastos_categoria'))

    op.drop_table('gastos')
    # ### end Alembic commands ###
