"""catalogo inicial

Revision ID: 2e6bfa0ca834
Revises: 
Create Date: 2026-09-16 21:50:27.085887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.tipos


# revision identifiers, used by Alembic.
revision: str = '2e6bfa0ca834'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_negocio', sa.String(length=150), nullable=False),
    sa.Column('nombre_contacto', sa.String(length=150), nullable=True),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('direccion', sa.String(length=300), nullable=True),
    sa.Column('dias_credito', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clientes'))
    )
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clientes_nombre_negocio'), ['nombre_negocio'], unique=False)

    op.create_table('proveedores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('contacto', sa.String(length=150), nullable=True),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('dias_credito', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_proveedores')),
    sa.UniqueConstraint('nombre', name=op.f('uq_proveedores_nombre'))
    )
    op.create_table('unidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clave', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('permite_decimales', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_unidades')),
    sa.UniqueConstraint('clave', name=op.f('uq_unidades_clave'))
    )
    op.create_table('direcciones_entrega',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(length=60), nullable=False),
    sa.Column('direccion', sa.String(length=300), nullable=False),
    sa.Column('referencia', sa.String(length=300), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], name=op.f('fk_direcciones_entrega_cliente_id_clientes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_direcciones_entrega'))
    )
    with op.batch_alter_table('direcciones_entrega', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_direcciones_entrega_cliente_id'), ['cliente_id'], unique=False)

    op.create_table('productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=30), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=False),
    sa.Column('unidad_id', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['unidad_id'], ['unidades.id'], name=op.f('fk_productos_unidad_id_unidades')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_productos')),
    sa.UniqueConstraint('codigo', name=op.f('uq_productos_codigo'))
    )
    op.create_table('precios_venta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('precio', app.tipos.DecimalFijo(), nullable=False),
    sa.Column('vigente_desde', sa.DateTime(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('precio >= 0', name=op.f('ck_precios_venta_precio_no_negativo')),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], name=op.f('fk_precios_venta_producto_id_productos')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_precios_venta')),
    sa.UniqueConstraint('producto_id', 'vigente_desde', name=op.f('uq_precios_venta_producto_id'))
    )
    op.create_table('proveedor_producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('unidad_compra_id', sa.Integer(), nullable=False),
    sa.Column('factor_conversion', app.tipos.DecimalFijo(), nullable=False),
    sa.Column('solo_unidades_completas', sa.Boolean(), nullable=False),
    sa.Column('es_preferido', sa.Boolean(), nullable=False),
    sa.Column('codigo_proveedor', sa.String(length=50), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('factor_conversion > 0', name=op.f('ck_proveedor_producto_factor_positivo')),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], name=op.f('fk_proveedor_producto_producto_id_productos')),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], name=op.f('fk_proveedor_producto_proveedor_id_proveedores')),
    sa.ForeignKeyConstraint(['unidad_compra_id'], ['unidades.id'], name=op.f('fk_proveedor_producto_unidad_compra_id_unidades')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_proveedor_producto')),
    sa.UniqueConstraint('proveedor_id', 'producto_id', name=op.f('uq_proveedor_producto_proveedor_id'))
    )
    with op.batch_alter_table('proveedor_producto', schema=None) as batch_op:
        batch_op.create_index('uq_proveedor_producto_un_preferido', ['producto_id'], unique=True, sqlite_where=sa.text('es_preferido = 1'), postgresql_where=sa.text('es_preferido'))

    op.create_table('costos_proveedor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proveedor_producto_id', sa.Integer(), nullable=False),
    sa.Column('costo', app.tipos.DecimalFijo(), nullable=False),
    sa.Column('vigente_desde', sa.DateTime(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('costo >= 0', name=op.f('ck_costos_proveedor_costo_no_negativo')),
    sa.ForeignKeyConstraint(['proveedor_producto_id'], ['proveedor_producto.id'], name=op.f('fk_costos_proveedor_proveedor_producto_id_proveedor_producto')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_costos_proveedor')),
    sa.UniqueConstraint('proveedor_producto_id', 'vigente_desde', name=op.f('uq_costos_proveedor_proveedor_producto_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('costos_proveedor')
    with op.batch_alter_table('proveedor_producto', schema=None) as batch_op:
        batch_op.drop_index('uq_proveedor_producto_un_preferido', sqlite_where=sa.text('es_preferido = 1'), postgresql_where=sa.text('es_preferido'))

    op.drop_table('proveedor_producto')
    op.drop_table('precios_venta')
    op.drop_table('productos')
    with op.batch_alter_table('direcciones_entrega', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_direcciones_entrega_cliente_id'))

    op.drop_table('direcciones_entrega')
    op.drop_table('unidades')
    op.drop_table('proveedores')
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clientes_nombre_negocio'))

    op.drop_table('clientes')
    # ### end Alembic commands ###
