"""cobros y pagos

Revision ID: 7252524fd1b8
Revises: a0b384286ebf
Create Date: 2026-09-19 12:53:54.617410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.tipos


# revision identifiers, used by Alembic.
revision: str = '7252524fd1b8'
down_revision: Union[str, Sequence[str], None] = 'a0b384286ebf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
