"""cobros y pagos

Revision ID: 84239108fdd1
Revises: a0b384286ebf
Create Date: 2026-09-19 13:32:47.957672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.tipos


# revision identifiers, used by Alembic.
revision: str = '84239108fdd1'
down_revision: Union[str, Sequence[str], None] = 'a0b384286ebf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pagos_proveedor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orden_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('monto', app.tipos.DecimalFijo(), nullable=False),
    sa.Column('metodo', sa.Enum('efectivo', 'transferencia', 'cheque', 'tarjeta', 'otro', name='metodopago', native_enum=False, length=20), nullable=False),
    sa.Column('referencia', sa.String(length=80), nullable=True),
    sa.Column('notas', sa.String(length=300), nullable=True),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('monto > 0', name=op.f('ck_pagos_proveedor_monto_positivo')),
    sa.ForeignKeyConstraint(['orden_id'], ['ordenes_compra.id'], name=op.f('fk_pagos_proveedor_orden_id_ordenes_compra')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pagos_proveedor'))
    )
    with op.batch_alter_table('pagos_proveedor', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pagos_proveedor_fecha'), ['fecha'], unique=False)
        batch_op.create_index(batch_op.f('ix_pagos_proveedor_orden_id'), ['orden_id'], unique=False)

    op.create_table('cobros_cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('monto', app.tipos.DecimalFijo(), nullable=False),
    sa.Column('metodo', sa.Enum('efectivo', 'transferencia', 'cheque', 'tarjeta', 'otro', name='metodopago', native_enum=False, length=20), nullable=False),
    sa.Column('referencia', sa.String(length=80), nullable=True),
    sa.Column('notas', sa.String(length=300), nullable=True),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('monto > 0', name=op.f('ck_cobros_cliente_monto_positivo')),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos_cliente.id'], name=op.f('fk_cobros_cliente_pedido_id_pedidos_cliente')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cobros_cliente'))
    )
    with op.batch_alter_table('cobros_cliente', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cobros_cliente_fecha'), ['fecha'], unique=False)
        batch_op.create_index(batch_op.f('ix_cobros_cliente_pedido_id'), ['pedido_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cobros_cliente', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cobros_cliente_pedido_id'))
        batch_op.drop_index(batch_op.f('ix_cobros_cliente_fecha'))

    op.drop_table('cobros_cliente')
    with op.batch_alter_table('pagos_proveedor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pagos_proveedor_orden_id'))
        batch_op.drop_index(batch_op.f('ix_pagos_proveedor_fecha'))

    op.drop_table('pagos_proveedor')
    # ### end Alembic commands ###
