"""ordenes de compra

Revision ID: a0b384286ebf
Revises: dcc503c823ca
Create Date: 2026-09-19 12:42:30.316079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.tipos


# revision identifiers, used by Alembic.
revision: str = 'a0b384286ebf'
down_revision: Union[str, Sequence[str], None] = 'dcc503c823ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ordenes_compra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=False),
    sa.Column('numero_remision', sa.String(length=50), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('fecha_recepcion', sa.Date(), nullable=True),
    sa.Column('dias_credito', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('borrador', 'enviada', 'recibida', 'cancelada', name='estadocompra', native_enum=False, length=20), nullable=False),
    sa.Column('notas', sa.String(length=500), nullable=True),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], name=op.f('fk_ordenes_compra_proveedor_id_proveedores')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ordenes_compra'))
    )
    with op.batch_alter_table('ordenes_compra', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ordenes_compra_estado'), ['estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_ordenes_compra_fecha'), ['fecha'], unique=False)
        batch_op.create_index(batch_op.f('ix_ordenes_compra_proveedor_id'), ['proveedor_id'], unique=False)

    op.create_table('orden_compra_lineas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orden_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=False),
    sa.Column('unidad_clave', sa.String(length=20), nullable=False),
    sa.Column('cantidad', app.tipos.DecimalFijo(), nullable=False),
    sa.Column('costo_unitario', app.tipos.DecimalFijo(), nullable=False),
    sa.Column('importe', app.tipos.DecimalFijo(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('cantidad > 0', name=op.f('ck_orden_compra_lineas_cantidad_positiva')),
    sa.CheckConstraint('costo_unitario >= 0', name=op.f('ck_orden_compra_lineas_costo_no_negativo')),
    sa.ForeignKeyConstraint(['orden_id'], ['ordenes_compra.id'], name=op.f('fk_orden_compra_lineas_orden_id_ordenes_compra')),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], name=op.f('fk_orden_compra_lineas_producto_id_productos')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orden_compra_lineas'))
    )
    with op.batch_alter_table('orden_compra_lineas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orden_compra_lineas_orden_id'), ['orden_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orden_compra_lineas_producto_id'), ['producto_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orden_compra_lineas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orden_compra_lineas_producto_id'))
        batch_op.drop_index(batch_op.f('ix_orden_compra_lineas_orden_id'))

    op.drop_table('orden_compra_lineas')
    with op.batch_alter_table('ordenes_compra', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ordenes_compra_proveedor_id'))
        batch_op.drop_index(batch_op.f('ix_ordenes_compra_fecha'))
        batch_op.drop_index(batch_op.f('ix_ordenes_compra_estado'))

    op.drop_table('ordenes_compra')
    # ### end Alembic commands ###
