"""clasificacion de clientes productos y vendedor

Revision ID: cc2648d23443
Revises: 84239108fdd1
Create Date: 2026-09-26 18:14:07.684546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.tipos


# revision identifiers, used by Alembic.
revision: str = 'cc2648d23443'
down_revision: Union[str, Sequence[str], None] = '84239108fdd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rfc', sa.String(length=13), nullable=True))
        batch_op.add_column(sa.Column('tipo_negocio', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('plaza', sa.String(length=60), nullable=True))
        batch_op.create_index(batch_op.f('ix_clientes_plaza'), ['plaza'], unique=False)
        batch_op.create_index(batch_op.f('ix_clientes_tipo_negocio'), ['tipo_negocio'], unique=False)

    with op.batch_alter_table('pedidos_cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vendedor', sa.String(length=60), nullable=True))
        batch_op.create_index(batch_op.f('ix_pedidos_cliente_vendedor'), ['vendedor'], unique=False)

    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categoria', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('familia', sa.String(length=60), nullable=True))
        batch_op.create_index(batch_op.f('ix_productos_categoria'), ['categoria'], unique=False)

    with op.batch_alter_table('proveedores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rfc', sa.String(length=13), nullable=True))
        batch_op.add_column(sa.Column('direccion', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proveedores', schema=None) as batch_op:
        batch_op.drop_column('direccion')
        batch_op.drop_column('rfc')

    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_productos_categoria'))
        batch_op.drop_column('familia')
        batch_op.drop_column('categoria')

    with op.batch_alter_table('pedidos_cliente', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pedidos_cliente_vendedor'))
        batch_op.drop_column('vendedor')

    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clientes_tipo_negocio'))
        batch_op.drop_index(batch_op.f('ix_clientes_plaza'))
        batch_op.drop_column('plaza')
        batch_op.drop_column('tipo_negocio')
        batch_op.drop_column('rfc')

    # ### end Alembic commands ###
