"""pedidos de cliente

Revision ID: dcc503c823ca
Revises: 2e6bfa0ca834
Create Date: 2026-09-16 22:15:31.248264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.tipos


# revision identifiers, used by Alembic.
revision: str = 'dcc503c823ca'
down_revision: Union[str, Sequence[str], None] = '2e6bfa0ca834'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pedidos_cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('direccion_entrega_id', sa.Integer(), nullable=True),
    sa.Column('direccion_entrega', sa.String(length=300), nullable=True),
    sa.Column('referencia_cliente', sa.String(length=50), nullable=True),
    sa.Column('fecha_pedido', sa.DateTime(), nullable=False),
    sa.Column('fecha_entrega', sa.Date(), nullable=True),
    sa.Column('dias_credito', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('borrador', 'confirmado', 'entregado', 'cancelado', name='estadopedido', native_enum=False, length=20), nullable=False),
    sa.Column('notas', sa.String(length=500), nullable=True),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], name=op.f('fk_pedidos_cliente_cliente_id_clientes')),
    sa.ForeignKeyConstraint(['direccion_entrega_id'], ['direcciones_entrega.id'], name=op.f('fk_pedidos_cliente_direccion_entrega_id_direcciones_entrega')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pedidos_cliente'))
    )
    with op.batch_alter_table('pedidos_cliente', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pedidos_cliente_cliente_id'), ['cliente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pedidos_cliente_estado'), ['estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_pedidos_cliente_fecha_pedido'), ['fecha_pedido'], unique=False)

    op.create_table('pedido_cliente_lineas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=False),
    sa.Column('unidad_clave', sa.String(length=20), nullable=False),
    sa.Column('cantidad', app.tipos.DecimalFijo(), nullable=False),
    sa.Column('precio_lista', app.tipos.DecimalFijo(), nullable=True),
    sa.Column('precio_unitario', app.tipos.DecimalFijo(), nullable=False),
    sa.Column('importe', app.tipos.DecimalFijo(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('cantidad > 0', name=op.f('ck_pedido_cliente_lineas_cantidad_positiva')),
    sa.CheckConstraint('precio_unitario >= 0', name=op.f('ck_pedido_cliente_lineas_precio_no_negativo')),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos_cliente.id'], name=op.f('fk_pedido_cliente_lineas_pedido_id_pedidos_cliente')),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], name=op.f('fk_pedido_cliente_lineas_producto_id_productos')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pedido_cliente_lineas')),
    sa.UniqueConstraint('pedido_id', 'producto_id', name=op.f('uq_pedido_cliente_lineas_pedido_id'))
    )
    with op.batch_alter_table('pedido_cliente_lineas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pedido_cliente_lineas_pedido_id'), ['pedido_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pedido_cliente_lineas_producto_id'), ['producto_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido_cliente_lineas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pedido_cliente_lineas_producto_id'))
        batch_op.drop_index(batch_op.f('ix_pedido_cliente_lineas_pedido_id'))

    op.drop_table('pedido_cliente_lineas')
    with op.batch_alter_table('pedidos_cliente', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pedidos_cliente_fecha_pedido'))
        batch_op.drop_index(batch_op.f('ix_pedidos_cliente_estado'))
        batch_op.drop_index(batch_op.f('ix_pedidos_cliente_cliente_id'))

    op.drop_table('pedidos_cliente')
    # ### end Alembic commands ###
